version: 2.1
jobs:
  compile-main:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: make
  run-scanner-test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: tests/bin/test_scanner
  run-ilist-test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: tests/bin/test_ilist

workflows:
  compile:
    jobs:
      - compile-main
      - run-scanner-test
      - run-ilist-test
